# Generated by Django 5.2.17 on 2026-09-30 07:59

import core.i18n
import core.imaging
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_variants', models.JSONField(blank=True, default=dict, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='title (English)')),
                ('short_description', models.CharField(help_text='One or two sentences shown on project cards.', max_length=300, verbose_name='short description (English)')),
                ('description', models.TextField(blank=True, help_text='Full case study text. Separate paragraphs with an empty line.', verbose_name='description (English)')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='client (English)')),
                ('deliverables', models.TextField(blank=True, help_text='One item per line.', verbose_name='deliverables (English)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='title (Arabic)')),
                ('short_description_ar', models.CharField(blank=True, max_length=300, verbose_name='short description (Arabic)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('client_ar', models.CharField(blank=True, max_length=150, verbose_name='client (Arabic)')),
                ('deliverables_ar', models.TextField(blank=True, verbose_name='deliverables (Arabic)')),
                ('slug', models.SlugField(help_text='Used in the URL: /en/projects/<slug>/', max_length=120, unique=True, verbose_name='slug')),
                ('category', models.CharField(choices=[('ai_video', 'AI Video'), ('ai_automation', 'AI & Automation'), ('web_development', 'Web Development'), ('digital_transformation', 'Digital Transformation')], db_index=True, max_length=32, verbose_name='category')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='year')),
                ('cover_image', models.ImageField(blank=True, help_text='Main visual (16:10 recommended, 2400px wide). Also used as the video poster.', upload_to=core.imaging.UploadTo('projects/covers'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), core.validators.validate_image_size], verbose_name='cover image')),
                ('cover_video', models.FileField(blank=True, help_text='Optional MP4/WebM. Plays muted as a preview on hover and on the project page.', upload_to=core.imaging.UploadTo('projects/videos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm']), core.validators.validate_video_size], verbose_name='cover video')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional image for the homepage card. Falls back to the cover image.', upload_to=core.imaging.UploadTo('projects/thumbnails'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), core.validators.validate_image_size], verbose_name='card thumbnail')),
                ('featured', models.BooleanField(default=False, help_text='Shown as a wide card.', verbose_name='featured')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title (English)')),
                ('seo_title_ar', models.CharField(blank=True, max_length=70, verbose_name='SEO title (Arabic)')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='SEO description (English)')),
                ('seo_description_ar', models.CharField(blank=True, max_length=170, verbose_name='SEO description (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['display_order', '-year', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'category'], name='projects_pr_is_publ_ef79a9_idx')],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_variants', models.JSONField(blank=True, default=dict, editable=False)),
                ('image', models.ImageField(blank=True, upload_to=core.imaging.UploadTo('projects/gallery'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), core.validators.validate_image_size], verbose_name='image')),
                ('video', models.FileField(blank=True, upload_to=core.imaging.UploadTo('projects/gallery'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm']), core.validators.validate_video_size], verbose_name='video')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption (English)')),
                ('caption_ar', models.CharField(blank=True, max_length=200, verbose_name='caption (Arabic)')),
                ('layout', models.CharField(choices=[('full', 'Full width'), ('half', 'Half width')], default='full', max_length=8, verbose_name='layout')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'verbose_name': 'gallery item',
                'verbose_name_plural': 'gallery',
                'ordering': ['order', 'pk'],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
    ]
