# Generated by Django 5.2.17 on 2026-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Public link to the running website or app (optional).', verbose_name='live site URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, help_text='Link to the code repository, e.g. GitHub (optional).', verbose_name='source code URL'),
        ),
    ]
