# Generated by Django 5.2.17 on 2026-09-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_fit',
            field=models.CharField(choices=[('fill', 'Fill the frame — photos and videos'), ('screen', 'Show the whole image — screenshots and interfaces')], default='fill', help_text='“Show the whole image” keeps screenshots uncropped on a dark frame. Applies to the cover and gallery images.', max_length=10, verbose_name='cover display'),
        ),
    ]
