# Generated by Django 5.2.17 on 2026-09-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_cover_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='also_in',
            field=models.JSONField(blank=True, default=list, help_text='Extra categories whose filter should also list this project (optional).', verbose_name='also show under'),
        ),
    ]
