# Generated by Django 5.2.17 on 2026-10-01 11:27

import core.imaging
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_also_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='film',
            field=models.FileField(blank=True, help_text='Optional complete video with sound, shown with a player on the project page. It loads only when the visitor presses play. Keep the cover video a short, light loop.', upload_to=core.imaging.UploadTo('projects/films'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm']), core.validators.validate_video_size], verbose_name='full film'),
        ),
    ]
