# Generated by Django 5.2.17 on 2026-10-01 11:38

import core.imaging
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_video_mobile',
            field=models.FileField(blank=True, help_text='Optional smaller copy of the cover video (about 960px wide) used on phones to save data.', upload_to=core.imaging.UploadTo('projects/videos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm']), core.validators.validate_video_size], verbose_name='cover video — phone version'),
        ),
        migrations.AddField(
            model_name='project',
            name='film_mobile',
            field=models.FileField(blank=True, help_text='Optional smaller copy of the full film (about 1280px wide) played on phones.', upload_to=core.imaging.UploadTo('projects/films'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm']), core.validators.validate_video_size], verbose_name='full film — phone version'),
        ),
    ]
