# Generated by Django 5.2.17 on 2026-09-30 07:59

import core.i18n
import core.imaging
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_variants', models.JSONField(blank=True, default=dict, editable=False)),
                ('label', models.CharField(default='Hero object', max_length=120, verbose_name='internal label')),
                ('image', models.ImageField(blank=True, help_text='Transparent PNG or WebP cut-out of the object. Around 1600×1600px works best.', upload_to=core.imaging.UploadTo('hero'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), core.validators.validate_image_size], verbose_name='object image')),
                ('video', models.FileField(blank=True, help_text='Optional short MP4/WebM loop (muted). Shown instead of the image.', upload_to=core.imaging.UploadTo('hero/video'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm']), core.validators.validate_video_size], verbose_name='object video')),
                ('video_poster', models.ImageField(blank=True, help_text='First frame of the video. Loaded before the video.', upload_to=core.imaging.UploadTo('hero/poster'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif']), core.validators.validate_image_size], verbose_name='video poster')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text (English)')),
                ('alt_text_ar', models.CharField(blank=True, max_length=200, verbose_name='alt text (Arabic)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hero media',
                'verbose_name_plural': 'hero media',
                'ordering': ['-updated_at'],
            },
            bases=(core.i18n.TranslatableMixin, models.Model),
        ),
    ]
