from django import template
from django.core.files.storage import default_storage
from django.urls import reverse

register = template.Library()


def _srcset(entries) -> str:
    return ", ".join(f"{default_storage.url(name)} {width}w" for width, name in entries)


@register.inclusion_tag("partials/picture.html")
def picture(obj, field, sizes="100vw", alt="", css="", loading="lazy", fetchpriority="auto", img_css=""):
    """
    Render a <picture> with AVIF/WebP srcsets generated by core.imaging.
    Falls back to the original upload when no variants exist.
    """
    field_file = getattr(obj, field, None) if obj is not None and field else None
    if not field_file:
        return {"empty": True}
    variants = obj.variants_for(field) if hasattr(obj, "variants_for") else {}
    webp = variants.get("webp") or []
    return {
        "empty": False,
        "avif": _srcset(variants.get("avif") or []),
        "webp": _srcset(webp),
        "src": default_storage.url(webp[-1][1]) if webp else field_file.url,
        "width": variants.get("width") or "",
        "height": variants.get("height") or "",
        "sizes": sizes,
        "alt": alt,
        "css": css,
        "img_css": img_css,
        "loading": loading,
        "fetchpriority": fetchpriority,
    }


@register.filter
def pad2(value):
    try:
        return f"{int(value):02d}"
    except (TypeError, ValueError):
        return value


@register.simple_tag(takes_context=True)
def anchor(context, section_id):
    """In-page hash on the homepage, full homepage URL + hash elsewhere."""
    if context.get("is_home"):
        return f"#{section_id}"
    return f"{reverse('core:home')}#{section_id}"


@register.simple_tag
def localized(obj, field):
    return obj.localized(field) if obj is not None else ""
