# Generated by Django 5.2.17 on 2026-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='company / business')),
                ('service', models.CharField(choices=[('ai_automation', 'AI & Automation'), ('web_development', 'Web Development'), ('ai_video', 'AI Video Generation'), ('digital_transformation', 'Digital Transformation'), ('other', 'Other')], max_length=32, verbose_name='service')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', max_length=2, verbose_name='preferred language')),
                ('message', models.TextField(verbose_name='message')),
                ('submitted_from', models.CharField(blank=True, editable=False, max_length=5, verbose_name='site language')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='received')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='read')),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
